@extends('layouts.app')

@section('title', 'Edit Transcript - Student Information System')

@section('content')
<div class="page-header">
    <h1>Edit Transcript</h1>
</div>

<div class="card" style="max-width: 600px;">
    <form action="{{ route('transcripts.update', $transcript->transcript_id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="student_id">Student *</label>
            <select id="student_id" name="student_id" required>
                <option value="">-- Select Student --</option>
                @foreach ($students as $student)
                    <option value="{{ $student->student_id }}" {{ old('student_id', $transcript->student_id) == $student->student_id ? 'selected' : '' }}>
                        {{ $student->first_name }} {{ $student->last_name }}
                    </option>
                @endforeach
            </select>
            @error('student_id') <span style="color: #dc3545; font-size: 0.875rem;">{{ $message }}</span> @enderror
        </div>

        <div class="form-group">
            <label for="date_generated">Date Generated *</label>
            <input type="date" id="date_generated" name="date_generated" value="{{ old('date_generated', $transcript->date_generated) }}" required>
            @error('date_generated') <span style="color: #dc3545; font-size: 0.875rem;">{{ $message }}</span> @enderror
        </div>

        <div class="form-group">
            <label for="generated_by_staff_id">Generated By (Staff ID) *</label>
            <input type="text" id="generated_by_staff_id" name="generated_by_staff_id" value="{{ old('generated_by_staff_id', $transcript->generated_by_staff_id) }}" required>
            @error('generated_by_staff_id') <span style="color: #dc3545; font-size: 0.875rem;">{{ $message }}</span> @enderror
        </div>

        <div class="form-group">
            <label for="file_path">File Path (Optional)</label>
            <input type="text" id="file_path" name="file_path" value="{{ old('file_path', $transcript->file_path) }}" placeholder="/path/to/transcript.pdf">
            @error('file_path') <span style="color: #dc3545; font-size: 0.875rem;">{{ $message }}</span> @enderror
        </div>

        <div class="btn-group" style="justify-content: flex-start; gap: 1rem;">
            <button type="submit" class="btn btn-success">Update Transcript</button>
            <a href="{{ route('transcripts.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
@endsection
