@extends('layouts.app')

@section('title', 'Transcripts - Student Information System')

@section('content')
<div class="page-header">
    <h1>Transcripts</h1>
    <a href="{{ route('transcripts.create') }}" class="btn btn-primary">+ Generate Transcript</a>
</div>

@if ($transcripts->count())
    <div class="card">
        <table class="table">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Generated Date</th>
                    <th>Generated By</th>
                    <th>File Path</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transcripts as $transcript)
                    <tr>
                        <td>{{ $transcript->student->first_name }} {{ $transcript->student->last_name }}</td>
                        <td>{{ $transcript->date_generated->format('M d, Y') }}</td>
                        <td>{{ $transcript->generated_by_staff_id }}</td>
                        <td>{{ $transcript->file_path ? pathinfo($transcript->file_path, PATHINFO_FILENAME) : 'N/A' }}</td>
                        <td>
                            <div class="btn-group" style="display: flex; gap: 8px; flex-wrap: wrap;">
                                <a href="{{ route('transcripts.show', $transcript->transcript_id) }}" class="btn btn-info" style="background-color: #17a2b8; color: white; padding: 8px 16px; border-radius: 4px; text-decoration: none; font-weight: 500; border: none; cursor: pointer; transition: background-color 0.3s;">👁️ View</a>
                                <a href="{{ route('transcripts.edit', $transcript->transcript_id) }}" class="btn btn-primary" style="background-color: #667eea; color: white; padding: 8px 16px; border-radius: 4px; text-decoration: none; font-weight: 500; border: none; cursor: pointer; transition: background-color 0.3s;">✏️ Edit</a>
                                <form action="{{ route('transcripts.destroy', $transcript->transcript_id) }}" method="POST" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this transcript?')">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger" style="background-color: #dc3545; color: white; padding: 8px 16px; border-radius: 4px; font-weight: 500; border: none; cursor: pointer; transition: background-color 0.3s;">🗑️ Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="pagination">
        {{ $transcripts->links() }}
    </div>
@else
    <div class="card">
        <p style="text-align: center; color: #999;">No transcripts found. <a href="{{ route('transcripts.create') }}">Generate one</a></p>
    </div>
@endif
@endsection
