@extends('layouts.app')

@section('title', 'Transcript Details - Student Information System')

@section('content')
<div class="page-header">
    <h1>Transcript Details</h1>
    <div class="btn-group">
        <a href="{{ route('transcripts.edit', $transcript->transcript_id) }}" class="btn btn-primary">Edit</a>
        <a href="{{ route('transcripts.index') }}" class="btn btn-secondary">Back</a>
    </div>
</div>

<div class="card">
    <h2>Transcript for {{ $transcript->student->first_name }} {{ $transcript->student->last_name }}</h2>
    
    <div class="detail-row">
        <label>Transcript ID:</label>
        <span>{{ $transcript->transcript_id }}</span>
    </div>
    
    <div class="detail-row">
        <label>Student:</label>
        <span>{{ $transcript->student->first_name }} {{ $transcript->student->last_name }}</span>
    </div>
    
    <div class="detail-row">
        <label>Student Email:</label>
        <span>{{ $transcript->student->email }}</span>
    </div>
    
    <div class="detail-row">
        <label>Date Generated:</label>
        <span>{{ $transcript->date_generated->format('M d, Y') }}</span>
    </div>
    
    <div class="detail-row">
        <label>Generated By (Staff ID):</label>
        <span>{{ $transcript->generated_by_staff_id }}</span>
    </div>
    
    @if($transcript->file_path)
    <div class="detail-row">
        <label>File Path:</label>
        <span>{{ $transcript->file_path }}</span>
    </div>
    @endif
</div>

<div class="card">
    <h3>Enrollment Summary</h3>
    @if($transcript->student->enrollments->count())
        <table class="table">
            <thead>
                <tr>
                    <th>Course Code</th>
                    <th>Course Name</th>
                    <th>Units</th>
                    <th>Grade</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transcript->student->enrollments as $enrollment)
                    <tr>
                        <td>{{ $enrollment->classSection->course->course_code }}</td>
                        <td>{{ $enrollment->classSection->course->course_name }}</td>
                        <td>{{ $enrollment->classSection->course->units }}</td>
                        <td>{{ $enrollment->grade ?? 'N/A' }}</td>
                        <td>{{ ucfirst($enrollment->status) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="text-align: center; color: #999;">No enrollments found for this student.</p>
    @endif
</div>
@endsection
