@extends('layouts.app')

@section('title', 'Student Details - Student Information System')

@section('content')
<div class="page-header">
    <h1>Student Details</h1>
    <div class="btn-group">
        <a href="{{ route('students.edit', $student->student_id) }}" class="btn btn-primary">Edit</a>
        <a href="{{ route('students.index') }}" class="btn btn-secondary">Back</a>
    </div>
</div>

<div class="card">
    <h2>{{ $student->first_name }} {{ $student->last_name }}</h2>
    
    <div class="detail-row">
        <label>Student ID:</label>
        <span>{{ $student->student_id }}</span>
    </div>
    
    <div class="detail-row">
        <label>Email:</label>
        <span>{{ $student->email }}</span>
    </div>
    
    <div class="detail-row">
        <label>Contact Number:</label>
        <span>{{ $student->contact_number }}</span>
    </div>
    
    <div class="detail-row">
        <label>Birth Date:</label>
        <span>{{ $student->birth_date->format('M d, Y') }}</span>
    </div>
    
    <div class="detail-row">
        <label>Address:</label>
        <span>{{ $student->address }}</span>
    </div>
    
    <div class="detail-row">
        <label>Enrollment Status:</label>
        <span>
            <span style="padding: 0.25rem 0.75rem; border-radius: 4px; background: 
                @if($student->enrollment_status == 'active') #d4edda; color: #155724;
                @elseif($student->enrollment_status == 'graduated') #d1ecf1; color: #0c5460;
                @elseif($student->enrollment_status == 'suspended') #f8d7da; color: #721c24;
                @else #e2e3e5; color: #383d41; @endif">
                {{ ucfirst($student->enrollment_status) }}
            </span>
        </span>
    </div>
</div>

@if($student->enrollments->count())
    <div class="card">
        <h3>Enrollments</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Course</th>
                    <th>Section</th>
                    <th>Date Enrolled</th>
                    <th>Status</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($student->enrollments as $enrollment)
                    <tr>
                        <td>{{ $enrollment->classSection->course->course_name }}</td>
                        <td>{{ $enrollment->classSection->section_code }}</td>
                        <td>{{ $enrollment->date_enrolled->format('M d, Y') }}</td>
                        <td>{{ ucfirst($enrollment->status) }}</td>
                        <td>{{ $enrollment->grade ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endif

@if($student->transcripts->count())
    <div class="card">
        <h3>Transcripts</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Generated Date</th>
                    <th>Generated By</th>
                    <th>File Path</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($student->transcripts as $transcript)
                    <tr>
                        <td>{{ $transcript->date_generated->format('M d, Y') }}</td>
                        <td>{{ $transcript->generated_by_staff_id }}</td>
                        <td>{{ $transcript->file_path ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endif
@endsection
