@extends('layouts.app')

@section('title', 'Student Dashboard')

@section('content')
<div class="dashboard-container">
    <div class="dashboard-header">
        <h1>📚 Student Dashboard</h1>
        <p>Welcome, {{ Auth::user()->full_name }}!</p>
    </div>

    <div class="stats-grid">
        <div class="stat-card">
            <div class="stat-icon">📝</div>
            <div class="stat-content">
                <h3>Active Enrollments</h3>
                <p class="stat-number">{{ $enrollmentCount }}</p>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon">📜</div>
            <div class="stat-content">
                <h3>Transcripts</h3>
                <p class="stat-number">{{ $transcriptCount }}</p>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon">👤</div>
            <div class="stat-content">
                <h3>Account Type</h3>
                <p class="stat-number">{{ ucfirst(Auth::user()->role) }}</p>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon">📧</div>
            <div class="stat-content">
                <h3>Email</h3>
                <p style="font-size: 0.9rem; word-break: break-all;">{{ Auth::user()->email }}</p>
            </div>
        </div>
    </div>

    @if($enrollmentCount > 0)
        <div class="section-card">
            <h2>My Current Enrollments</h2>
            <div class="enrollment-list">
                @foreach($activeEnrollments as $enrollment)
                    <div class="enrollment-item">
                        <div class="enrollment-info">
                            <h4>{{ $enrollment->classSection->course->course_name }}</h4>
                            <p><strong>Code:</strong> {{ $enrollment->classSection->course->course_code }}</p>
                            <p><strong>Instructor:</strong> {{ $enrollment->classSection->instructor->first_name }} {{ $enrollment->classSection->instructor->last_name }}</p>
                            <p><strong>Schedule:</strong> {{ $enrollment->classSection->schedule }}</p>
                            <p><strong>Room:</strong> {{ $enrollment->classSection->room }}</p>
                        </div>
                        <div class="enrollment-status">
                            <span class="status-badge {{ strtolower($enrollment->status) }}">
                                {{ ucfirst($enrollment->status) }}
                            </span>
                            @if($enrollment->grade)
                                <p style="margin-top: 10px;"><strong>Grade:</strong> {{ $enrollment->grade }}</p>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    @else
        <div class="section-card">
            <p style="text-align: center; color: #666;">No active enrollments. <a href="{{ route('enrollments.index') }}">View all enrollments</a></p>
        </div>
    @endif

    @if($transcriptCount > 0)
        <div class="section-card">
            <h2>Academic Transcripts</h2>
            <div class="transcript-list">
                @foreach($transcripts as $transcript)
                    <div class="transcript-item">
                        <p><strong>Generated by:</strong> {{ $transcript->staff_id }}</p>
                        <p><strong>Date:</strong> {{ $transcript->created_at->format('M d, Y') }}</p>
                        <a href="{{ route('transcripts.show', $transcript->transcript_id) }}" class="btn btn-primary">View</a>
                    </div>
                @endforeach
            </div>
        </div>
    @endif

    <div class="quick-links">
        <h3>Quick Links</h3>
        <div class="links-grid">
            <a href="{{ route('students.show', $student->student_id ?? '#') }}" class="quick-link">👁️ View Profile</a>
            <a href="{{ route('enrollments.index') }}" class="quick-link">📝 All Enrollments</a>
            <a href="{{ route('transcripts.index') }}" class="quick-link">📜 Transcripts</a>
            <a href="{{ route('academic_courses.index') }}" class="quick-link">📖 Course Catalog</a>
        </div>
    </div>
</div>

<style>
    .dashboard-container {
        max-width: 1000px;
        margin: 0 auto;
    }

    .dashboard-header {
        text-align: center;
        margin-bottom: 40px;
        color: #333;
    }

    .dashboard-header h1 {
        font-size: 2.5rem;
        margin-bottom: 10px;
    }

    .dashboard-header p {
        font-size: 1.1rem;
        color: #666;
    }

    .stats-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        gap: 20px;
        margin-bottom: 40px;
    }

    .stat-card {
        background: white;
        border-radius: 10px;
        padding: 25px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        display: flex;
        align-items: center;
        gap: 20px;
        border-left: 5px solid #667eea;
    }

    .stat-icon {
        font-size: 2.5rem;
        flex-shrink: 0;
    }

    .stat-content h3 {
        margin: 0;
        color: #666;
        font-size: 0.9rem;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .stat-number {
        margin: 10px 0 0 0;
        font-size: 2rem;
        font-weight: bold;
        color: #333;
    }

    .section-card {
        background: white;
        border-radius: 10px;
        padding: 30px;
        margin-bottom: 25px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .section-card h2 {
        margin-top: 0;
        margin-bottom: 25px;
        color: #333;
        border-bottom: 2px solid #f0f0f0;
        padding-bottom: 15px;
    }

    .enrollment-list {
        display: grid;
        gap: 15px;
    }

    .enrollment-item {
        background: #f9f9f9;
        border-left: 4px solid #667eea;
        padding: 20px;
        border-radius: 6px;
        display: flex;
        justify-content: space-between;
        align-items: start;
        gap: 20px;
    }

    .enrollment-info {
        flex: 1;
    }

    .enrollment-info h4 {
        margin: 0 0 10px 0;
        color: #333;
        font-size: 1.1rem;
    }

    .enrollment-info p {
        margin: 8px 0;
        color: #666;
        font-size: 0.95rem;
    }

    .enrollment-status {
        text-align: center;
    }

    .status-badge {
        display: inline-block;
        padding: 8px 16px;
        border-radius: 20px;
        font-weight: 600;
        font-size: 0.85rem;
    }

    .status-badge.active {
        background-color: #d4edda;
        color: #155724;
    }

    .status-badge.completed {
        background-color: #d1ecf1;
        color: #0c5460;
    }

    .status-badge.dropped {
        background-color: #f8d7da;
        color: #721c24;
    }

    .transcript-list {
        display: grid;
        gap: 15px;
    }

    .transcript-item {
        background: #f9f9f9;
        border-left: 4px solid #43e97b;
        padding: 20px;
        border-radius: 6px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        gap: 20px;
    }

    .transcript-item p {
        margin: 5px 0;
        color: #666;
    }

    .quick-links {
        background: white;
        border-radius: 10px;
        padding: 30px;
        margin-bottom: 40px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }

    .quick-links h3 {
        margin-top: 0;
        margin-bottom: 20px;
        color: #333;
        border-bottom: 2px solid #f0f0f0;
        padding-bottom: 15px;
    }

    .links-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 15px;
    }

    .quick-link {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 15px;
        border-radius: 8px;
        text-decoration: none;
        font-weight: 500;
        text-align: center;
        transition: transform 0.3s, box-shadow 0.3s;
    }

    .quick-link:hover {
        transform: translateY(-3px);
        box-shadow: 0 5px 20px rgba(102, 126, 234, 0.4);
    }
</style>
@endsection
